name: Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 20.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 20
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ZUPIT_BOT_NPM_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ZUPIT_BOT_NPM_TOKEN }}
